from app.features.chat_ai_reply.prompts import AI_CHAT_REPLY_SYSTEM_PROMPT
from app.features.chat_translation.prompts import CHAT_MESSAGE_TRANSLATION_PROMPT
from app.features.language_learning.level_test.prompts import (
    LEVEL_TEST_CHOICE_SEMANTIC_VERIFICATION_SYSTEM_PROMPT,
    LEVEL_TEST_GENERATION_SYSTEM_PROMPT,
    LEVEL_TEST_SPEAKING_EVALUATION_SYSTEM_PROMPT,
    LEVEL_TEST_TASK_SUFFICIENCY_VERIFICATION_SYSTEM_PROMPT,
    LEVEL_TEST_VOCAB_CONTEXT_DESIGN_SYSTEM_PROMPT,
    LEVEL_TEST_VOCAB_CONTEXT_REPAIR_SYSTEM_PROMPT,
)
from app.features.language_learning.speaking.prompts import (
    SPEAKING_CONVERSATION_SYSTEM_PROMPT,
    SPEAKING_EVALUATION_SYSTEM_PROMPT,
)
from app.features.language_learning.listening.prompts import (
    LISTENING_EXPLANATION_SYSTEM_PROMPT,
    LISTENING_GENERATION_SYSTEM_PROMPT,
    LISTENING_INTERPRETATION_SYSTEM_PROMPT,
    LISTENING_SUMMARY_SYSTEM_PROMPT,
)
from app.features.language_learning.writing.prompts import (
    DAILY_WRITING_GENERATION_SYSTEM_PROMPT,
    LEVEL_TEST_QUESTION_SYSTEM_PROMPT,
    WRITING_EVALUATION_SYSTEM_PROMPT,
)
from app.features.receipt.prompts import RECEIPT_ANALYSIS_PROMPT
from app.features.translation.prompts import TRANSLATION_PROMPT_MAP
from app.features.voice_translation.prompts import VOICE_TRANSLATION_SYSTEM_PROMPT

PROMPT_MAP = {
    **TRANSLATION_PROMPT_MAP,
    "RECEIPT_ANALYSIS": RECEIPT_ANALYSIS_PROMPT,
    "CHAT_MESSAGE_TRANSLATION": CHAT_MESSAGE_TRANSLATION_PROMPT,
    "AI_CHAT_REPLY": AI_CHAT_REPLY_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_DAILY_WRITING_GENERATION": DAILY_WRITING_GENERATION_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_WRITING_EVALUATION": WRITING_EVALUATION_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_LEVEL_TEST_QUESTION": LEVEL_TEST_QUESTION_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_LEVEL_TEST_V2_GENERATION": LEVEL_TEST_GENERATION_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_LEVEL_TEST_V2_VOCAB_CONTEXT_DESIGN": LEVEL_TEST_VOCAB_CONTEXT_DESIGN_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_LEVEL_TEST_V2_VOCAB_CONTEXT_REPAIR": LEVEL_TEST_VOCAB_CONTEXT_REPAIR_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_LEVEL_TEST_V2_CHOICE_VERIFICATION": LEVEL_TEST_CHOICE_SEMANTIC_VERIFICATION_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_LEVEL_TEST_V2_TASK_SUFFICIENCY_VERIFICATION": LEVEL_TEST_TASK_SUFFICIENCY_VERIFICATION_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_LEVEL_TEST_V2_SPEAKING_EVALUATION": LEVEL_TEST_SPEAKING_EVALUATION_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_SPEAKING_CONVERSATION": SPEAKING_CONVERSATION_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_SPEAKING_EVALUATION": SPEAKING_EVALUATION_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_LISTENING_GENERATION": LISTENING_GENERATION_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_LISTENING_INTERPRETATION": LISTENING_INTERPRETATION_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_LISTENING_SUMMARY_EVALUATION": LISTENING_SUMMARY_SYSTEM_PROMPT,
    "LANGUAGE_LEARNING_LISTENING_EXPLANATION": LISTENING_EXPLANATION_SYSTEM_PROMPT,
    "VOICE_TRANSLATION": VOICE_TRANSLATION_SYSTEM_PROMPT,
}


def get_prompt_rule(type_name: str) -> str | None:
    return PROMPT_MAP.get(type_name)
